"""Provider-agnostic canonical cache protocol.

Single source of truth for token-cache concepts across the MarkBot stack.
Every provider adapter normalises its raw ``usage`` dict into a
:class:`CanonicalUsage` instance, and the rest of the agent (cost
tracker, prefix-stability manager, TUI chips) only ever reads canonical
fields.

## Why

Different providers expose cache statistics under different names:

================  =======================  =====================
Provider          Hit bucket               Miss / write bucket
================  =======================  =====================
Anthropic         ``cache_read_input``     ``cache_creation_input``
OpenAI Codex      ``prompt_cache_hit``     ``prompt_cache_miss``
DeepSeek          ``prompt_cache_hit``     ``prompt_cache_miss``
Gemini            ``cached_content_token`` ``(none)``
================  =======================  =====================

Storing a single :class:`CanonicalUsage` per request lets the rest of
the agent compare apples-to-apples and avoid duplicated "is this
provider Anthropic?" branches scattered across the codebase.

## Discipline

- ``None`` is the correct sentinel for *unknown* (provider did not
  report cache stats).  Do **not** coerce to ``0``; "unknown" is not
  the same as "zero hits".
- All counts are non-negative 64-bit integers.
- :class:`CacheEvent` carries the prefix-stability signal that the
  TUI subscribes to via the bus.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Canonical token usage
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CanonicalUsage:
    """Provider-agnostic normalised token-usage snapshot.

    All fields default to ``None`` (meaning *unknown*).  When the
    provider did not report the corresponding bucket, the field stays
    ``None`` and downstream code must treat it as "no data" rather
    than as "0 hits".
    """

    # ------------------------------------------------------------------
    # Core buckets
    # ------------------------------------------------------------------
    #: Tokens billed at the cache-miss / uncached rate.
    input_tokens: Optional[int] = None
    #: Tokens generated by the model.
    output_tokens: Optional[int] = None

    # ------------------------------------------------------------------
    # Cache buckets (5-bucket model, inspired by Hermes)
    # ------------------------------------------------------------------
    #: Tokens served from the server-side prefix cache (cheap).
    cache_read_tokens: Optional[int] = None
    #: Tokens written into the server-side prefix cache this turn.
    cache_creation_tokens: Optional[int] = None
    #: Tokens billed at the uncached rate because the prefix did not
    #: match.  Some providers report this explicitly (DeepSeek, Codex);
    #: others do not, in which case the field stays ``None``.
    cache_miss_tokens: Optional[int] = None

    # ------------------------------------------------------------------
    # Reasoning / thinking
    # ------------------------------------------------------------------
    #: Hidden reasoning tokens (o1, Claude extended thinking, R1).
    reasoning_tokens: Optional[int] = None
    #: Tokens replayed from a previous reasoning trace (Anthropic
    #: thinking replay).  Some agents re-inject these to preserve
    #: cross-turn thinking context.
    reasoning_replay_tokens: Optional[int] = None

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------
    #: Source provider name (for debug / metrics).
    provider: Optional[str] = None
    #: Opaque raw usage dict, kept for observability backends
    #: (Langfuse, OpenTelemetry) that need the original keys.
    raw: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Derived helpers
    # ------------------------------------------------------------------
    @property
    def total_input(self) -> int:
        """Sum of all input-side buckets (or ``input_tokens`` alone if
        cache buckets are unknown).  Always returns a non-negative
        integer — never raises on missing data.
        """
        if self.input_tokens is None:
            return 0
        base = self.input_tokens
        if self.cache_read_tokens is not None:
            base += self.cache_read_tokens
        if self.cache_creation_tokens is not None:
            base += self.cache_creation_tokens
        return base

    @property
    def total_output(self) -> int:
        """Output + reasoning, since reasoning tokens are billed."""
        out = self.output_tokens or 0
        out += self.reasoning_tokens or 0
        return out

    @property
    def cache_hit_rate(self) -> Optional[float]:
        """Fraction of input tokens served from cache.

        Returns ``None`` when the provider did not report cache
        statistics — explicitly *not* ``0.0``.  Callers must check
        ``is None`` before displaying "0%".
        """
        if self.cache_read_tokens is None:
            return None
        denominator = self.cache_read_tokens
        if self.cache_miss_tokens is not None:
            denominator += self.cache_miss_tokens
        elif self.input_tokens is not None:
            denominator += self.input_tokens
        if denominator == 0:
            return None
        return max(0.0, min(1.0, self.cache_read_tokens / denominator))

    def merge(self, other: "CanonicalUsage") -> "CanonicalUsage":
        """Combine two usage snapshots (e.g. for subagent aggregation).

        Per-bucket fields are summed; provider / raw carry the *first*
        non-None value seen (callers that need both can read
        ``self.raw`` / ``other.raw``).
        """
        def _add(a, b):
            if a is None and b is None:
                return None
            return (a or 0) + (b or 0)

        return CanonicalUsage(
            input_tokens=_add(self.input_tokens, other.input_tokens),
            output_tokens=_add(self.output_tokens, other.output_tokens),
            cache_read_tokens=_add(self.cache_read_tokens, other.cache_read_tokens),
            cache_creation_tokens=_add(self.cache_creation_tokens, other.cache_creation_tokens),
            cache_miss_tokens=_add(self.cache_miss_tokens, other.cache_miss_tokens),
            reasoning_tokens=_add(self.reasoning_tokens, other.reasoning_tokens),
            reasoning_replay_tokens=_add(self.reasoning_replay_tokens, other.reasoning_replay_tokens),
            provider=self.provider or other.provider,
            raw={**self.raw, **other.raw},
        )


# ---------------------------------------------------------------------------
# Provider adapter contract
# ---------------------------------------------------------------------------

class UsageNormaliser:
    """Mixin / adapter for converting a provider's raw ``usage`` dict
    into a :class:`CanonicalUsage`.

    Each provider subclass overrides :meth:`normalise` and declares
    which keys it reads.  The :meth:`from_response` helper extracts
    the dict from an :class:`LLMResponse`-shaped object.
    """

    #: Keys this provider exposes for cache hits / writes / misses.
    #: Override in subclass.
    cache_read_key: Optional[str] = None
    cache_creation_key: Optional[str] = None
    cache_miss_key: Optional[str] = None

    def normalise(self, usage: dict[str, Any] | None) -> CanonicalUsage:
        if not usage:
            return CanonicalUsage()
        cache_read = self._pick(usage, self.cache_read_key) if self.cache_read_key else None
        cache_creation = self._pick(usage, self.cache_creation_key) if self.cache_creation_key else None
        cache_miss = self._pick(usage, self.cache_miss_key) if self.cache_miss_key else None
        input_tokens = self._pick(usage, "input_tokens", "prompt_tokens")
        # Synthesise the miss bucket when the provider only reports
        # cache_read + cache_creation (e.g. Anthropic) or just
        # ``cached_input_tokens`` (e.g. Codex Responses).  We treat
        # the residual ``input - read - creation`` as the miss.
        if cache_miss is None and input_tokens is not None:
            residual = input_tokens
            if cache_read is not None:
                residual -= cache_read
            if cache_creation is not None:
                residual -= cache_creation
            if residual > 0:
                cache_miss = residual
        return CanonicalUsage(
            input_tokens=input_tokens,
            output_tokens=self._pick(usage, "output_tokens", "completion_tokens"),
            cache_read_tokens=cache_read,
            cache_creation_tokens=cache_creation,
            cache_miss_tokens=cache_miss,
            reasoning_tokens=self._pick(usage, "reasoning_tokens"),
            reasoning_replay_tokens=self._pick(usage, "reasoning_replay_tokens"),
            provider=self.__class__.__name__,
            raw=dict(usage),
        )

    @staticmethod
    def _pick(d: dict[str, Any], *keys: Optional[str]) -> Optional[int]:
        for k in keys:
            if k is None:
                continue
            v = d.get(k)
            if v is not None:
                try:
                    return int(v)
                except (TypeError, ValueError):
                    continue
        return None


# ---------------------------------------------------------------------------
# Cache events (bus payload)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CacheEvent:
    """A single prefix-stability observation emitted by the agent loop.

    The TUI / observability layer subscribes to these to render the
    "cache hit %" chip and the "prefix drift" notice.

    Attributes:
        description: Human-readable summary (e.g. "sys+tools", "stable").
        system_prompt_changed: True iff the system prompt bytes changed.
        tools_changed: True iff the tool catalog hash changed.
        stability_pct: 0-100 — fraction of recent turns that were stable.
        changed: True iff this is a real drift (vs. a heartbeat observation).
        pinned_combined_hash: Short form of the pinned combined hash.
        cache_read_tokens: From the most recent LLM response, if any.
        cache_miss_tokens: From the most recent LLM response, if any.
    """

    description: str
    system_prompt_changed: bool = False
    tools_changed: bool = False
    stability_pct: int = 100
    changed: bool = False
    pinned_combined_hash: str = ""
    cache_read_tokens: Optional[int] = None
    cache_miss_tokens: Optional[int] = None

    @property
    def label(self) -> str:
        """Short tag for the TUI / log line."""
        if not self.changed:
            return "stable"
        if self.system_prompt_changed and self.tools_changed:
            return "sys+tools"
        if self.system_prompt_changed:
            return "sys"
        if self.tools_changed:
            return "tools"
        return "prefix"

    @property
    def hit_rate(self) -> Optional[float]:
        if self.cache_read_tokens is None or self.cache_miss_tokens is None:
            return None
        total = self.cache_read_tokens + self.cache_miss_tokens
        if total == 0:
            return None
        return self.cache_read_tokens / total
