"""Shared type definitions for markbot."""

from markbot.types.exceptions import (
    AuthenticationError,
    BudgetExceededError,
    ConfigError,
    ConfigMigrationError,
    ConfigValidationError,
    FatalError,
    InvalidParamsError,
    MarkbotError,
    ModelNotFoundError,
    PermissionDeniedError,
    PIIExposureError,
    QuotaExceededError,
    RateLimitError,
    SecurityError,
    ServiceUnavailableError,
    SessionCorruptedError,
    SessionError,
    SessionWriteError,
    SSRFError,
    TimeoutError,
    TransientError,
)
from markbot.types.permission import PermissionDecision, PermissionMode, ToolPermissionContext
from markbot.types.skill import SkillConditions, SkillConfigVar, SkillDefinition, SkillScriptDef
from markbot.types.tool import ToolContext, ToolDefinition, ToolParameter

__all__ = [
    "MarkbotError",
    "TransientError",
    "RateLimitError",
    "TimeoutError",
    "ServiceUnavailableError",
    "FatalError",
    "AuthenticationError",
    "QuotaExceededError",
    "ModelNotFoundError",
    "InvalidParamsError",
    "ConfigError",
    "ConfigValidationError",
    "ConfigMigrationError",
    "SessionError",
    "SessionCorruptedError",
    "SessionWriteError",
    "BudgetExceededError",
    "PermissionDeniedError",
    "SecurityError",
    "PIIExposureError",
    "SSRFError",
    "PermissionMode",
    "PermissionDecision",
    "ToolPermissionContext",
    "ToolParameter",
    "ToolDefinition",
    "ToolContext",
    "SkillScriptDef",
    "SkillDefinition",
    "SkillConfigVar",
    "SkillConditions",
]
