"""Shared type definitions for markbot."""

from markbot.types.exceptions import (
    MarkbotError,
    TransientError,
    RateLimitError,
    TimeoutError,
    ServiceUnavailableError,
    FatalError,
    AuthenticationError,
    QuotaExceededError,
    ModelNotFoundError,
    InvalidParamsError,
    ConfigError,
    ConfigValidationError,
    ConfigMigrationError,
    SessionError,
    SessionCorruptedError,
    SessionWriteError,
    BudgetExceededError,
    PermissionDeniedError,
    SecurityError,
    PIIExposureError,
    SSRFError,
)
from markbot.types.permission import PermissionMode, PermissionDecision, ToolPermissionContext
from markbot.types.tool import ToolParameter, ToolDefinition, ToolContext
from markbot.types.skill import SkillScriptDef, SkillDefinition, SkillConfigVar, SkillConditions

__all__ = [
    "MarkbotError",
    "TransientError",
    "RateLimitError",
    "TimeoutError",
    "ServiceUnavailableError",
    "FatalError",
    "AuthenticationError",
    "QuotaExceededError",
    "ModelNotFoundError",
    "InvalidParamsError",
    "ConfigError",
    "ConfigValidationError",
    "ConfigMigrationError",
    "SessionError",
    "SessionCorruptedError",
    "SessionWriteError",
    "BudgetExceededError",
    "PermissionDeniedError",
    "SecurityError",
    "PIIExposureError",
    "SSRFError",
    "PermissionMode",
    "PermissionDecision",
    "ToolPermissionContext",
    "ToolParameter",
    "ToolDefinition",
    "ToolContext",
    "SkillScriptDef",
    "SkillDefinition",
    "SkillConfigVar",
    "SkillConditions",
]
